//
// Created by Cyril on 23/06/2021.
//

#ifndef VERTICES_SDK_EXAMPLES_ESP32_MAIN_CONFIG_H
#define VERTICES_SDK_EXAMPLES_ESP32_MAIN_CONFIG_H

#define SERVER_URL          "https://api.testnet.algoexplorer.io"
#define SERVER_PORT         0
#define SERVER_TOKEN_HEADER ""

#define ACCOUNT_RECEIVER    "27J56E73WOFSEQUECLRCLRNBV3D74H7BYB7USEXCJOYPLBTACULABWMLVU"

#define APP_ID 16037129

#endif //VERTICES_SDK_EXAMPLES_ESP32_MAIN_CONFIG_H
